<a href="https://colab.research.google.com/github/sierrastarbrady/COMM557/blob/master/NBA_INJURY_ANALYSIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1) NBA Injuries Dataset
Main dataset used for KMeans clustering; for documentation please refer to, https://www.kaggle.com/datasets/ghopkins/nba-injuries-2010-2018?resource=download

### Goals 
1. Clean and preprocess dataset (remove null columns and rename features) 


2. Research and implement key feature engineering techniques 
    - (One-hot-encoding for vectorization, and possibly use PCA (Principle Component Analysis), NLP (Natural Language processing) or topic modeling
    
    
3. Begin clustering vectors found from one-hot encoding using KMeans Algorithm and assess performance

In [ ]:
import pandas as pd
import numpy as np
df1 = pd.read_csv('/NBA DATA/injuries_2010-2020.csv')
df1.head(50)

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out inde...
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out ind...
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
5,2010-10-08,Pistons,NaN,Jonas Jerebko,surgery to repair torn right Achilles tendon
6,2010-10-08,Pistons,NaN,Terrico White,surgery on right foot to repair broken fifth m...
7,2010-10-09,Nuggets,NaN,Al Harrington,partially torn plantar fascia in left foot (ou...
8,2010-10-12,Bucks,NaN,Darington Hobson,surgery on left hip (out for season)
9,2010-10-12,Kings,NaN,Samuel Dalembert,strained left groin (out indefinitely)
10,2010-10-17,Bobcats,NaN,Dominic McGuire,stress fracture in left shin (out indefinitely)
11,2010-10-18,Warriors,NaN,Lou Amundson,surgery to repair fractured right index finger...
12,2010-10-19,Suns,NaN,Josh Childress,fractured right index finger (out indefinitely)
13,2010-10-22,Heat,NaN,Mike Miller,surgery on right hand to repair a broken thumb...
14,2010-10-25,Thunder,NaN,Nick Collison,left knee injury (out indefinitely)
15,2010-10-25,Timberwolves,NaN,Martell Webster,surgery on back (out indefinitely)
16,2010-10-26,Blazers,NaN,Elliot Williams,placed on IL
17,2010-10-26,Blazers,NaN,Greg Oden,placed on IL with left knee injury (out for se...
18,2010-10-26,Blazers,NaN,Joel Przybilla,placed on IL placed on IL recovering from surg...
19,2010-10-26,Celtics,NaN,Avery Bradley,placed on IL recovering from surgery on left a...
20,2010-10-26,Celtics,NaN,Kendrick Perkins,placed on IL recovering from surgery on right ...
21,2010-10-26,Celtics,NaN,Luke Harangody,placed on IL
22,2010-10-26,Heat,NaN,Dexter Pittman,placed on IL
23,2010-10-26,Heat,NaN,Jerry Stackhouse,placed on IL
24,2010-10-26,Heat,NaN,Mario Chalmers,sprained ankle (out indefinitely)
25,2010-10-26,Heat,NaN,Mike Miller,placed on IL recovering from surgery on right ...
26,2010-10-26,Lakers,NaN,Andrew Bynum,placed on IL recovering from surgery on right ...
27,2010-10-26,Lakers,NaN,Luke Walton,placed on IL with strained right hamstring
28,2010-10-26,Rockets,NaN,Jermaine Taylor,placed on IL
29,2010-10-26,Rockets,NaN,Kyle Lowry,placed on IL with back spasms
30,2010-10-26,Rockets,NaN,Patrick Patterson,placed on IL
31,2010-10-26,Suns,NaN,Gani Lawal,placed on IL
32,2010-10-26,Suns,NaN,Matt Janning,placed on IL
33,2010-10-27,76ers,NaN,Craig Brackins,placed on IL
34,2010-10-27,76ers,NaN,Jodie Meeks,placed on IL
35,2010-10-27,Bobcats,NaN,Dominic McGuire,placed on IL with stress fracture in left shin
36,2010-10-27,Bobcats,NaN,Eduardo Najera,placed on IL with sports hernia
37,2010-10-27,Bobcats,NaN,Kwame Brown,placed on IL with sprained left ankle
38,2010-10-27,Bucks,NaN,Chris Douglas-Roberts,placed on IL with right eye injury
39,2010-10-27,Bucks,NaN,Jon Brockman,sprained left ankle (DNP)
40,2010-10-27,Bucks,NaN,Luc Mbah a Moute,sprained right ankle (DNP)
41,2010-10-27,Bucks,NaN,Michael Redd,placed on IL recovering from surgery on left k...
42,2010-10-27,Bulls,NaN,Carlos Boozer,placed on IL with fractured bone in right pink...
43,2010-10-27,Cavaliers,NaN,Christian Eyenga,placed on IL
44,2010-10-27,Cavaliers,NaN,Mo Williams,placed on IL with groin injury
45,2010-10-27,Cavaliers,NaN,Samardo Samuels,placed on IL
46,2010-10-27,Clippers,NaN,Craig Smith,placed on IL with back injury
47,2010-10-27,Clippers,NaN,Willie Warren,placed on IL
48,2010-10-27,Grizzlies,NaN,Greivis Vasquez,placed on IL recovering from surgery on right ...
49,2010-10-27,Grizzlies,NaN,Marc Gasol,placed on IL with sprained right ankle / left ...

In [ ]:
df1.shape

(36436, 5)

In [ ]:
df1.describe()

              Date   Team       Acquired Relinquished              Notes
count        36436  36433          13506        22924              36435
unique        2104     32           1112         1156               3114
top     2017-04-12  Spurs  Kawhi Leonard  Eric Gordon  activated from IL
freq           148   1512             81          123              10367

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36436 entries, 0 to 36435
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          36436 non-null  object
 1   Team          36433 non-null  object
 2   Acquired      13506 non-null  object
 3   Relinquished  22924 non-null  object
 4   Notes         36435 non-null  object
dtypes: object(5)
memory usage: 1.4+ MB

In [ ]:
#Run cell to find each unique description in dataset (Beware the output is large)
unique_descriptions = df1['Notes'].unique()

# print the unique descriptions
for description in unique_descriptions:
    print(description)

In [ ]:
# Run cell to find each unique Team
unique_descriptions1 = df1['Team'].unique()

for d in unique_descriptions1:
    print(d)

Bulls
Pistons
Blazers
Nets
Nuggets
Bucks
Kings
Bobcats
Warriors
Suns
Heat
Thunder
Timberwolves
Celtics
Lakers
Rockets
76ers
Cavaliers
Clippers
Grizzlies
Hawks
Hornets
Jazz
Knicks
Mavericks
Pacers
Raptors
Spurs
Magic
Wizards
Pelicans
nan
Bullets

In [ ]:
df1["Notes"].value_counts()
#Going to need to figure out how to encode the last few words in sentence to a unique identifier

activated from IL                                              10367
placed on IL                                                    4467
returned to lineup                                              3021
placed on IL with illness                                        444
rest (DTD)                                                       370
                                                               ...
surgery to repair fractured orbital bone (out indefinitely)        1
sprained left ankle (P) / knee (CBC) (DNP)                         1
fractured left cheekbone (DNP)                                     1
placed on IL with hip injury (P)                                   1
surgery on right toe to repair fracture (out indefinitely)         1
Name: Notes, Length: 3114, dtype: int64

In [ ]:
#Find sum of null values
null_feats_1 = df1["Team"].isnull().sum()
null_feats_2 = df1["Acquired"].isnull().sum()
null_feats_3 = df1["Relinquished"].isnull().sum()

print("There are", null_feats_1 ,"null entries in the Team column")
print("There are", null_feats_2 ,"null entries in the Acquired column")
print("There are", null_feats_3 ,"null entries in the Relinquished column")

There are 3 null entries in the Team column
There are 22930 null entries in the Acquired column
There are 13512 null entries in the Relinquished column

## 2) NBA Player Stats (NOT WORKING IN COLLAB RIGHT NOW)
Information on key player stats to use for predictions; for documentation please refer to https://data.world/etocco/nba-player-stats

In [ ]:
df2 = pd.read_csv('/NBA DATA/nba_player_stats.csv')
df2

ParserError: ignored

In [ ]:
df3 = pd.read_csv('nba_player_stats_2.csv')
df3

,rk,player,pos,age,tm,g,gs,mp,fg,fga,...,drb,trb,ast,stl,blk,tov,pf,pts,season,mvp
0,1,Mahmoud Abdul-Rauf,PG,28,SAC,31,0,17.1,3.3,8.8,...,1.0,1.2,1.9,0.5,0.0,0.6,1.0,7.3,1997-98,False
1,2,Tariq Abdul-Wahad,SG,23,SAC,59,16,16.3,2.4,6.1,...,1.2,2.0,0.9,0.6,0.2,1.1,1.4,6.4,1997-98,False
2,3,Shareef Abdur-Rahim,SF,21,VAN,82,82,36.0,8.0,16.4,...,4.3,7.1,2.6,1.1,0.9,3.1,2.5,22.3,1997-98,False
3,4,Cory Alexander,PG,24,TOT,60,22,21.6,2.9,6.7,...,2.2,2.4,3.5,1.2,0.2,1.9,1.6,8.1,1997-98,False
4,4,Cory Alexander,PG,24,SAS,37,3,13.5,1.6,3.9,...,1.1,1.3,1.9,0.7,0.1,1.3,1.4,4.5,1997-98,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14568,601,Thaddeus Young,PF,33,TOR,26,0,18.3,2.6,5.5,...,2.9,4.4,1.7,1.2,0.4,0.8,1.7,6.3,2021-22,False
14569,602,Trae Young,PG,23,ATL,76,76,34.9,9.4,20.3,...,3.1,3.7,9.7,0.9,0.1,4.0,1.7,28.4,2021-22,False
14570,603,Omer Yurtseven,C,23,MIA,56,12,12.6,2.3,4.4,...,3.7,5.3,0.9,0.3,0.4,0.7,1.5,5.3,2021-22,False
14571,604,Cody Zeller,C,29,POR,27,0,13.1,1.9,3.3,...,2.8,4.6,0.8,0.3,0.2,0.7,2.1,5.2,2021-22,False
14572,605,Ivica Zubac,C,24,LAC,76,76,24.4,4.1,6.5,...,5.6,8.5,1.6,0.5,1.0,1.5,2.7,10.3,2021-22,False

## 3) NBA API Data

For documentation on how to use API to find player information please refer to https://github.com/swar/nba_api
- Before running make sure to open anaconda terminal and input: pip install nba_api

### Official NBA Stats

In [ ]:
from nba_api.stats.endpoints import playercareerstats

# Nikola Jokić
career = playercareerstats.PlayerCareerStats(player_id='203999') 

# pandas data frames (optional: pip install pandas)
career.get_data_frames()[0]

# json
career.get_json()

# dictionary
career.get_dict()

### NBA Live Data

In [ ]:
from nba_api.live.nba.endpoints import scoreboard

# Today's Score Board
games = scoreboard.ScoreBoard()

# json
games.get_json()

# dictionary
games.get_dict()